# action.yaml
name: 'Custom Docker Action'
description: 'Runs Docker commands using the Docker official image.'
inputs:
  who-to-greet:
    description: 'Person to greet.'
    required: true
runs:
  using: 'docker'
  image: 'docker:latest'
  
