name: 'Custom Docker Action'
description: 'A custom action using an Alpine Linux image with Docker installed to execute a script.'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'alpine:latest'
  args:
    - /workspace/entrypoint.sh  # Specify the script to run inside the container
