name: 'Docker Container Action with Existing Image'
description: 'A GitHub Action that uses an existing Docker image and installs Python dependencies'

inputs:
  python_dependencies:
    description: 'Python dependencies to install'
    required: true

outputs:
  python_dependencies_installed:
    description: 'Indicates whether Python dependencies were successfully installed'

runs:
  using: 'docker'
  image: 'docker://alpine:3.17'
  entrypoint: /entrypoint.sh
  args:
  - -c
  - |
    set -e
    
    # Copy entrypoint.sh from the Docker image repository to the current directory inside the container
    cp /entrypoint.sh .
    
    # Make entrypoint.sh executable
    chmod +x ./entrypoint.sh
    
    # Execute entrypoint.sh with the provided python_dependencies
    ./entrypoint.sh "${{ inputs.python_dependencies }}"
