name: 'Docker Container Action with Existing Image'
description: 'A GitHub Action that uses an existing Docker image and installs Python dependencies'

inputs:
  python_dependencies:
    description: 'Python dependencies to install'
    required: true

outputs:
  python_dependencies_installed:
    description: 'Indicates whether Python dependencies were successfully installed'

runs:
  using: 'docker'
  image: 'docker://ubuntu:latest' # Using the Ubuntu Docker image
  entrypoint: '/bin/bash'
  args:
    - -c
    - |
      set -e
      
      # Update package list and install Python and pip3
      apt-get update && apt-get install -y python3 python3-pip
      
      # Debugging: List contents of root directory
      ls -l /
      
      # Copy entrypoint.sh from the GitHub repository to /entrypoint.sh inside the container
      cp entrypoint.sh /entrypoint.sh
      
      # Ensure entrypoint.sh has executable permissions
      chmod +x /entrypoint.sh
      
      # Execute entrypoint.sh with the provided python_dependencies
      /entrypoint.sh "${{ inputs.python_dependencies }}"
