name: 'Simple Docker Container Action'
description: 'An action that uses an existing Docker image'

inputs:
  greeting:
    description: 'A greeting message'
    required: true
    default: 'Hello, World!'
outputs:
  result:
    description: 'The processed greeting'
runs:
  using: 'docker'
  image: 'alpine:latest'  # This uses the official Alpine Linux image as an example
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - 'echo "${{ inputs.greeting }}" > /github/workspace/greeting.txt'

