name: 'Custom Action'
description: 'Run custom action script in a Docker container'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker:latest'
  args:
    - sh
    - -c
    - |
      docker run -v $(pwd):/workspace -w /workspace docker://docker:latest sh -c "cp ./entrypoint.sh /workspace/ && chmod +x /workspace/entrypoint.sh && /workspace/entrypoint.sh '${{ inputs.who-to-greet }}'"
