name: 'Hello World'
description: 'Prints a hello world message'
inputs:
  name:
    description: 'The name to include in the hello message'
    required: true
runs:
  using: 'docker'
  image: 'docker://alpine:latest'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      chmod +x /script.sh
      /script.sh $INPUT_NAME
