name: 'My Docker Action'
description: 'An example GitHub Action using a public Docker image as the runtime environment'
runs:
  using: 'docker'
  image: 'docker://docker:latest'
  args:
    - ${{ github.workspace }}
