name: 'Hello World'
description: 'Prints a hello world message'
runs:
  using: 'docker'
  image: 'docker://alpine:latest'
  entrypoint: /bin/sh
  args:
    - -c
    - |
      chmod +x /script.sh
      /script.sh
