name: Test Docker Container Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Container Action
        uses: vinod1002/Existing-docker-image@main
        with:
          greeting: 'Hello from GitHub Actions!'
