name: Test Docker Container Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Container Action
        uses: yourusername/docker-container-action-exist-image@master
        with:
          greeting: 'Hello from GitHub Actions!'
      
      - name: Check Greeting File
        run: cat greeting.txt
