name: Custom Action Workflow

on: [push]

jobs:
  custom_action_job:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Custom Action
      run: |
        docker run -v $(pwd):/workspace -w /workspace your_selected_image:tag sh -c "./custom_action.sh"
