name: Test Docker Container Action

on: [push]

jobs:
  test_action:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Test Docker Container Action
        uses: ./ # Assumes the action is in the root directory of your repository
        with:
          python_dependencies: '${{ github.event.inputs.python-dependencies }}'
