name: Custom Action Workflow

on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        required: true
        default: 'World'

jobs:
  custom_action_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker run -d -v $(pwd):/workspace alpine:latest tail -f /dev/null
          docker exec $(docker ps -lq) mkdir -p /workspace  # Create /workspace directory inside the container

      - name: Copy entrypoint.sh to Docker container
        run: |
          docker cp entrypoint.sh $(docker ps -lq):/workspace/entrypoint.sh
          docker exec $(docker ps -lq) chmod +x /workspace/entrypoint.sh

      - name: Execute Custom Docker Action
        uses: ./
        with:
          who-to-greet: ${{ github.event.inputs.who-to-greet }}

      - name: Clean up Docker container
        run: docker rm -f $(docker ps -lq)
