name: Custom Action Workflow

on:
  workflow_dispatch:
   
jobs:
  custom_action_job:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display current directory contents
        run: ls -l

      - name: Run Custom Action
        uses: ./

      - name: Set up Docker
        run: |
          docker run -d -v $(pwd):/workspace alpine:latest tail -f /dev/null
          docker exec $(docker ps -lq) mkdir -p /workspace  # Ensure /workspace directory exists inside the container
      
      - name: Copy script to Docker container & Execute the script 
        run: | 
          docker cp entrypoint.sh $(docker ps -lq):/workspace/entrypoint.sh
          docker exec $(docker ps -lq) chmod +x /workspace/entrypoint.sh
          docker exec $(docker ps -lq) sh /workspace/entrypoint.sh ${{ github.event.inputs.who-to-greet }}

      - name: Clean up Docker container
        run: docker rm -f $(docker ps -lq)
