name: Custom Action Workflow

on: [push]

jobs:
  custom_action_job:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set executable permission
      run: chmod +x custom_action.sh

    - name: Run Custom Action
      run: |
        docker run -v $(pwd):/workspace -w /workspace docker:latest sh -c "./custom_action.sh"
